### Custom menu
### See https://stack.jimmycai.com/config/menu
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
main: []

social:
  - identifier: github
    name: GitHub
    url: https://github.com/osguider/blog
    params:
      icon: brand-github

  # - identifier: twitter
  #   name: Twitter
  #   url: https://twitter.com
  #   params:
  #       icon: brand-twitter
