
mainSections:
  - post
featuredImageField: image
rssFullContent: true
favicon:  /blog/favicon.svg # e.g.: favicon placed in `static/favicon.ico` of your site folder, then set this field to `/favicon.ico` (`/` is necessary)

footer:
  since: 2023
  customText:

dateFormat:
  published: 2006/01/02
  lastUpdated: 2006/01/02 15:04

sidebar:
  emoji:
  subtitle: 发现开源之美，碰撞无限可能
  avatar:
    enabled: true
    local: true
    src: images/logo/opensource-guider-white-circle.png

article:
  math: false
  toc: true
  readingTime: true
  license:
    enabled: true
    default: Licensed under CC BY-NC-SA 4.0

comments:
  enabled: false
  provider: disqus

  disqusjs:
    shortname:
    apiUrl:
    apiKey:
    admin:
    adminLabel:

  utterances:
    repo:
    issueTerm: pathname
    label:

  remark42:
    host:
    site:
    locale:

  vssue:
    platform:
    owner:
    repo:
    clientId:
    clientSecret:
    autoCreateIssue: false

  # Waline client configuration see: https://waline.js.org/en/reference/component.html
  waline:
    serverURL:
    lang:
    pageview:
    emoji:
        - https://unpkg.com/@waline/emojis@1.0.1/weibo
    requiredMeta:
        - name
        - email
        - url
    locale:
        admin: Admin
        placeholder:

  twikoo:
    envId:
    region:
    path:
    lang:

  # See https://cactus.chat/docs/reference/web-client/#configuration for description of the various options
  cactus:
    defaultHomeserverUrl: "https://matrix.cactus.chat:8448"
    serverName: "cactus.chat"
    siteName: "" # You must insert a unique identifier here matching the one you registered (See https://cactus.chat/docs/getting-started/quick-start/#register-your-site)

  giscus:
    repo:
    repoID:
    category:
    categoryID:
    mapping:
    lightTheme:
    darkTheme:
    reactionsEnabled: 1
    emitMetadata: 0

  gitalk:
    owner:
    admin:
    repo:
    clientID:
    clientSecret:

  cusdis:
    host:
    id:
widgets:
  homepage:
    - type: search
    - type: archives
      params:
        limit: 2
    - type: categories
      params:
        limit: 5
    - type: tag-cloud
      params:
        limit: 20
  page:
    - type: toc

opengraph:
  twitter:
    # Your Twitter username
    site: osguider

    # Available values: summary, summary_large_image
    card: summary_large_image

defaultImage:
  opengraph:
    enabled: true
    local: false
    src: https://hello-world-misty-lake-c367.903481591.workers.dev

colorScheme:
  # Display toggle
  toggle: true

  # Available values: auto, light, dark
  default: auto

imageProcessing:
  cover:
    enabled: true
  content:
    enabled: true
